/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecordingsRouteImport } from './routes/_authenticated/recordings'
import { Route as AuthenticatedLegacyRouteImport } from './routes/_authenticated/legacy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team.index'
import { Route as AuthenticatedTeamEmployeeIdRouteImport } from './routes/_authenticated/team.$employeeId'
import { Route as AuthenticatedRecordingsIdRouteImport } from './routes/_authenticated/recordings.$id'
import { Route as AuthenticatedMeetingsNewRouteImport } from './routes/_authenticated/meetings.new'
import { Route as AuthenticatedMeetingsIdRouteImport } from './routes/_authenticated/meetings.$id'
import { Route as AuthenticatedFeedbackNewRouteImport } from './routes/_authenticated/feedback.new'

const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordingsRoute = AuthenticatedRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegacyRoute = AuthenticatedLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamEmployeeIdRoute =
  AuthenticatedTeamEmployeeIdRouteImport.update({
    id: '/team/$employeeId',
    path: '/team/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordingsIdRoute =
  AuthenticatedRecordingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRecordingsRoute,
  } as any)
const AuthenticatedMeetingsNewRoute =
  AuthenticatedMeetingsNewRouteImport.update({
    id: '/meetings/new',
    path: '/meetings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsIdRoute = AuthenticatedMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackNewRoute =
  AuthenticatedFeedbackNewRouteImport.update({
    id: '/feedback/new',
    path: '/feedback/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manual': typeof ManualRoute
  '/pitch': typeof PitchRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/legacy': typeof AuthenticatedLegacyRoute
  '/recordings': typeof AuthenticatedRecordingsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/recordings/$id': typeof AuthenticatedRecordingsIdRoute
  '/team/$employeeId': typeof AuthenticatedTeamEmployeeIdRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manual': typeof ManualRoute
  '/pitch': typeof PitchRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/legacy': typeof AuthenticatedLegacyRoute
  '/recordings': typeof AuthenticatedRecordingsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/recordings/$id': typeof AuthenticatedRecordingsIdRoute
  '/team/$employeeId': typeof AuthenticatedTeamEmployeeIdRoute
  '/team': typeof AuthenticatedTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/manual': typeof ManualRoute
  '/pitch': typeof PitchRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/legacy': typeof AuthenticatedLegacyRoute
  '/_authenticated/recordings': typeof AuthenticatedRecordingsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/_authenticated/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/_authenticated/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/_authenticated/recordings/$id': typeof AuthenticatedRecordingsIdRoute
  '/_authenticated/team/$employeeId': typeof AuthenticatedTeamEmployeeIdRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manual'
    | '/pitch'
    | '/analytics'
    | '/dashboard'
    | '/legacy'
    | '/recordings'
    | '/reports'
    | '/feedback/new'
    | '/meetings/$id'
    | '/meetings/new'
    | '/recordings/$id'
    | '/team/$employeeId'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manual'
    | '/pitch'
    | '/analytics'
    | '/dashboard'
    | '/legacy'
    | '/recordings'
    | '/reports'
    | '/feedback/new'
    | '/meetings/$id'
    | '/meetings/new'
    | '/recordings/$id'
    | '/team/$employeeId'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/manual'
    | '/pitch'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/legacy'
    | '/_authenticated/recordings'
    | '/_authenticated/reports'
    | '/_authenticated/feedback/new'
    | '/_authenticated/meetings/$id'
    | '/_authenticated/meetings/new'
    | '/_authenticated/recordings/$id'
    | '/_authenticated/team/$employeeId'
    | '/_authenticated/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ManualRoute: typeof ManualRoute
  PitchRoute: typeof PitchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recordings': {
      id: '/_authenticated/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof AuthenticatedRecordingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legacy': {
      id: '/_authenticated/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof AuthenticatedLegacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$employeeId': {
      id: '/_authenticated/team/$employeeId'
      path: '/team/$employeeId'
      fullPath: '/team/$employeeId'
      preLoaderRoute: typeof AuthenticatedTeamEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recordings/$id': {
      id: '/_authenticated/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof AuthenticatedRecordingsIdRouteImport
      parentRoute: typeof AuthenticatedRecordingsRoute
    }
    '/_authenticated/meetings/new': {
      id: '/_authenticated/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthenticatedMeetingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings/$id': {
      id: '/_authenticated/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AuthenticatedMeetingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/new': {
      id: '/_authenticated/feedback/new'
      path: '/feedback/new'
      fullPath: '/feedback/new'
      preLoaderRoute: typeof AuthenticatedFeedbackNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRecordingsRouteChildren {
  AuthenticatedRecordingsIdRoute: typeof AuthenticatedRecordingsIdRoute
}

const AuthenticatedRecordingsRouteChildren: AuthenticatedRecordingsRouteChildren =
  {
    AuthenticatedRecordingsIdRoute: AuthenticatedRecordingsIdRoute,
  }

const AuthenticatedRecordingsRouteWithChildren =
  AuthenticatedRecordingsRoute._addFileChildren(
    AuthenticatedRecordingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLegacyRoute: typeof AuthenticatedLegacyRoute
  AuthenticatedRecordingsRoute: typeof AuthenticatedRecordingsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedFeedbackNewRoute: typeof AuthenticatedFeedbackNewRoute
  AuthenticatedMeetingsIdRoute: typeof AuthenticatedMeetingsIdRoute
  AuthenticatedMeetingsNewRoute: typeof AuthenticatedMeetingsNewRoute
  AuthenticatedTeamEmployeeIdRoute: typeof AuthenticatedTeamEmployeeIdRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLegacyRoute: AuthenticatedLegacyRoute,
  AuthenticatedRecordingsRoute: AuthenticatedRecordingsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedFeedbackNewRoute: AuthenticatedFeedbackNewRoute,
  AuthenticatedMeetingsIdRoute: AuthenticatedMeetingsIdRoute,
  AuthenticatedMeetingsNewRoute: AuthenticatedMeetingsNewRoute,
  AuthenticatedTeamEmployeeIdRoute: AuthenticatedTeamEmployeeIdRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ManualRoute: ManualRoute,
  PitchRoute: PitchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
